services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: zso_socket_proxy
    restart: unless-stopped
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - NETWORKS=1
      - SERVICES=1
    networks:
      proxy-network:
        aliases:
          - socket-proxy

  traefik:
    image: traefik:latest
    container_name: zso_apps_proxy
    restart: unless-stopped
    command:
      - "--log.level=${TRAEFIK_LOG_LEVEL}"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=tcp://socket-proxy:2375"
      - "--entrypoints.web.address=:${PROXY_HTTP_PORT}"
      - "--entrypoints.websecure.address=:${PROXY_HTTPS_PORT}"
      - "--entrypoints.websecure.http.tls=true"
      - "--providers.file.filename=/conf/tls.yml"
    ports:
      - "${PROXY_HTTP_PORT}:${PROXY_HTTP_PORT}"
      - "${PROXY_HTTPS_PORT}:${PROXY_HTTPS_PORT}"
    volumes:
      - ./conf:/conf:ro
    networks:
      - proxy-network
    depends_on:
      - socket-proxy

networks:
  proxy-network:
    external: true
