services:
  offlinekarte-search-db:
    networks:
      - proxy-network
      - default

  offlinekarte-search:
    ports: !override
      - "${OFFLINEKARTE_SEARCHSERVER_PORT}:8000"
    env_file:
      - .env
    networks:
      - proxy-network
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy-network"
      - "traefik.http.routers.offline-search-http.entrypoints=web"
      - "traefik.http.routers.offline-search-http.rule=Host(`${OFFLINEKARTE_SEARCHSERVER_DOMAIN}`)"
      - "traefik.http.routers.offline-search-http.service=offline-search-service"
      - "traefik.http.routers.offline-search-http.middlewares=offline-search-redirect"
      - "traefik.http.middlewares.offline-search-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.offline-search-secure.entrypoints=websecure"
      - "traefik.http.routers.offline-search-secure.rule=Host(`${OFFLINEKARTE_SEARCHSERVER_DOMAIN}`)"
      - "traefik.http.routers.offline-search-secure.tls=true"
      - "traefik.http.routers.offline-search-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.offline-search-secure.service=offline-search-service"
      - "traefik.http.services.offline-search-service.loadbalancer.server.port=8000"

  offlinekarte-tileserver:
    env_file:
      - .env
    environment:
      - TILESERVER_GL_ALLOWED_HOSTS=${TILESERVER_GL_ALLOWED_HOSTS:-${OFFLINEKARTE_TILESERVER_DOMAIN}}
    networks:
      - proxy-network
      - default
    ports: !override
      - "${OFFLINEKARTE_TILESERVER_PORT}:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy-network"
      - "traefik.http.routers.offline-tiles-http.entrypoints=web"
      - "traefik.http.routers.offline-tiles-http.rule=Host(`${OFFLINEKARTE_TILESERVER_DOMAIN}`)"
      - "traefik.http.routers.offline-tiles-http.service=offline-tiles-service"
      - "traefik.http.routers.offline-tiles-http.middlewares=offline-tiles-redirect"
      - "traefik.http.middlewares.offline-tiles-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.offline-tiles-secure.entrypoints=websecure"
      - "traefik.http.routers.offline-tiles-secure.rule=Host(`${OFFLINEKARTE_TILESERVER_DOMAIN}`)"
      - "traefik.http.routers.offline-tiles-secure.tls=true"
      - "traefik.http.routers.offline-tiles-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.offline-tiles-secure.service=offline-tiles-service"
      - "traefik.http.services.offline-tiles-service.loadbalancer.server.port=8080"

networks:
  proxy-network:
    external: true
